/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import org.junit.Test;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Random;
import java.util.Scanner;

import static org.junit.Assert.*;

public class AppTest {
//    Gson gson = new Gson();
//    Random randomNumber = new Random();
//    String root = System.getProperty("user.dir");
//    String filePath = root+File.separator+"app/src/main/resources/recentquotes.json";
//    Scanner readFile = new Scanner(new File(filePath));
//    StringBuilder quotes = new StringBuilder();
//        while(readFile.hasNextLine()){
//        quotes.append(readFile.nextLine());
//    }
//    Quote[] allQuotes = gson.fromJson(quotes.toString(), Quote[].class);
//
//    public AppTest() throws FileNotFoundException {
//    }
//
//    @Test public void appHasAGreeting() {
//        App classUnderTest = new App();
//        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
//
//    }
//    @Test public void testTheGsonNull()  {
//        assertNotNull(quotes[randomNumber].getText());
//        assertNotNull(quotes[randomNumber].getAuthor());
//    }

//    @Test public void testTheGsonExistence(){
//        assertEquals("author:" + "Marilyn Monroe" + ", text:" +"“I am good, but not an angel. I do sin, but I am not the devil. I am just a small girl in a big world trying to find someone to love.”"
//                ,quotes.toString());
//    }
}
